try{
    const a_20;
    
}
catch(err){
    console.log(err)
}